FROM oven/bun:1-alpine as build
WORKDIR /usr/src/bot

COPY package.json ./
RUN bun install

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/ ./docker

ENTRYPOINT /usr/src/bot/docker/entrypoint-dev.sh
