version: "3"

networks:
  fiibot-moderation:
    external: false

services:
  bot:
    build:
      context: ".."
      dockerfile: "./docker/Dockerfile.dev"
    volumes:
      - "..:/usr/src/bot"
    networks:
      - fiibot-moderation
    env_file:
      - "../.env"
    tty: true
  db:
    image: "postgres:15.1-alpine"
    env_file:
      - "../.env"
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - fiibot-moderation
    ports:
      - "5432:5432"
  redis:
    image: "redis:7.0.8-alpine"
    networks:
      - fiibot-moderation
