FROM node:18-alpine3.17 as build
WORKDIR /usr/src/bot

COPY package*.json ./
RUN npm install
RUN npm i -g nodemon

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/ ./docker

ENTRYPOINT /usr/src/bot/docker/entrypoint-dev.sh
